apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
  labels:
    labs: lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      labs: lab2
  template:
    metadata:
      labels:
        labs: lab2
    spec:
      containers:
      - name: itdt
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "Mikhail Kudryashov"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO"

---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec: 
  type: NodePort
  selector: 
    labs: lab2
  ports:
    - port: 3000

