apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
  labels:
    labs: lab2
spec:
  REACT_APP_USERNAME: Mikhail Kudryashov
  REACT_APP_COMPANY_NAME: ITMO
  replicas: 2
  selector:
    matchLabels:
      labs: lab2
  template:
    metadata:
      labels:
        labs: lab2
    spec:
      containers:
      - name: itdt
        image: ifilyaninitmo/itdt-contained-frontend
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec: 
  type: NodePort
  selector: 
    labs: lab2
  ports:
    - port: 3000
